### ISSUE TITLE
Improve input validation for Email Address

### ISSUE THREAD

**Issue by D3luxee** [mailcow/mailcow-dockerized#1017]
Hello everyone,

While debugging another issue here i found a new one. It is possible to create mails like 

> "\"\\\"huehue\\\"\""@neuland.tech
But its not possible to send mails with it, edit or delete it afterwards. It is also possible to do some html injection in this way.

Like this:

>"\"\\\"\\\\\\\\\"root@localhost<i.am.root&now.you.are.not>\\\\\\\\\"\\\"\""@neuland.tech

![2018-02-09-233045_1573x171_scrot](https://user-images.githubusercontent.com/10009528/36053335-a302cfd8-0df1-11e8-969a-b4576849a759.png)

The input validation should be improved to avoid such issues.

**Comment by andryyy** [comment]
I cannot create those mailboxes in the UI.

Keep in mind that a valid mail address can contain some weird symbols. :-)

**Comment by D3luxee** [comment]
I know, thats how i found this issue try this:

`"\"\\\"\\\\\\\\\"root@localhost<i.am.root&now.you.are.not>\\\\\\\\\"\\\"\""`
Its a valid local part of a email address referring to RFC 5322 and https://en.wikipedia.org/wiki/Email_address

I've played with this yesterday and the interpretation of this weird mail addresses vary alot between the different software components used by mailcow.

If you take a look at the allowed characters by a simple email address you will be suprised.

> !#$%&'*+-/=?^_`{|}~;

And those are allowed if you put them into double quotes:

`"(),:;<>@[\]`

Thats all you need for html tags and stuff.

I guess you have to decide which characters mailcow want to offer, maybe we can check how the big email providers handle this.

Thunderbird for example cant handle such email addresses, the login into SoGo worked but it was not possible to send emails.

![2018-02-10-124434_1081x191_scrot](https://user-images.githubusercontent.com/10009528/36061824-8a193254-0e60-11e8-9ea5-9d2c5431659a.png)

I've tried this mail address which is a example from the wiki page for a valid email address and it was rejected by mailcow at the creation:

> "()<>[]:,;@\\\"!#$%&'-/=?^_`{}| ~.a"@neuland.tech

**Comment by andryyy** [comment]
Are you on dev? I fixed the encodings, hopefully.

**Comment by D3luxee** [comment]
No im not on dev currently, i will setup a dev mailcow now and check this.

**Comment by MAGICCC** [comment]
Can add/remove `"\"\\\"\\\\\\\\\"root@localhost<i.am.root&now.you.are.not>\\\\\\\\\"\\\"\""` as mailbox username on https://github.com/mailcow/mailcow-dockerized/commit/78870995d0fc7b9a590e31c39d62cb34c4067207
But it's still not escaped: 
![6f9](https://user-images.githubusercontent.com/3279213/36064806-15f0828e-0e91-11e8-857e-d81eb8b602ed.png)

Also editing doesn't work as well - blank page:
![35e](https://user-images.githubusercontent.com/3279213/36064810-2bc33250-0e91-11e8-9253-fdb6fe47be50.png)

**Comment by D3luxee** [comment]
Since @MAGICCC can add and remove this mail the encoding seems to be fixed, but its still possible to break the html with this mail address.
And we should check the effects on SoGo with this mail addresses.

**Comment by andryyy** [comment]
The html view is fixed, you just need to clean your cache. :-) But editing fails, that's true.

As long as it is RFC-conform, we should allow any address.

Edit: Sorry, my previous push failed.

**Comment by MAGICCC** [comment]
Tried it with some browsers and the last \> is still visible.
Also deactivating fails as well with `Username cannot be used` thus [Username is invalid](https://github.com/mailcow/mailcow-dockerized/blob/ee87d5cb670c811f52b04179153175c0592b79fa/data/web/lang/lang.en.php#L66)

**Comment by D3luxee** [comment]
The html overview is not fixed as you will see on the images below.
I've tested this with a fresh installed firefox and in a incognito tab.

![2018-02-10-185101_1068x97_scrot](https://user-images.githubusercontent.com/10009528/36064961-bf02ca42-0e93-11e8-8bcc-5f0b00d37e99.png)
![2018-02-10-185113_489x109_scrot](https://user-images.githubusercontent.com/10009528/36064962-bf1c5ea8-0e93-11e8-9cf4-987cff7aef08.png)

As you can see the 

> \\\\\\\\\"\\\"\""@blaettner.tech" />
got handled as plain text and is not within any html tag.

**NVM i did not see your latest commit and the dev mailcow was outdated**
Update;

I can remove them and the html view is fixed, **but the edit page does not work**

**Comment by MAGICCC** [comment]
Ah just saw that you pushed something. Add/Remove/Activate/Deactivate works, but Edit is still empty. And HTML is also fine now
dev I am on is https://github.com/mailcow/mailcow-dockerized/commit/4163f0800952e35f3d2335b666bcf7a419708c1b

**Comment by andryyy** [comment]
Yes, that was my previous fix, it failed to push due to a missing pull... didn't see that.

**Comment by D3luxee** [comment]
The edit page is still empty and SoGo doesn't seem to support names such as

> "\"\\\"\\\\\\\\\"root@localhost<i.am.root&now.you.are.not>\\\\\\\\\"\\\"\""@neuland.tech

The login just fails, i will try to send mails if i can find any mailclient supporting those mails.

**Comment by andryyy** [comment]
It is not empty, I am just now using it. You may not have pulled the latest "fix". I am trying to fix some more issues about encoding right now.

**Comment by D3luxee** [comment]
With 8e1ac0b it is possible to edit the mail addresses but i cant delete or activate / deactivate them.

Error: `Benutzername kann nicht verwendet werden`

Great work so far, i can't wait to send some mails with those email address :)

**Comment by andryyy** [comment]
Sec, will push more fixes. :-) I am still working on it. It is kind of fun, but also annoying. :-D

**Comment by MAGICCC** [comment]
Yes seems to work now!

**Comment by D3luxee** [comment]
I can also confirm, its working now. Time to check mailtransfer and other components like SoGo.

**Comment by D3luxee** [comment]
* Login into the mailcow ui with this user is working
* Login into SoGo fails if the address contains " and /
* Mailcow Documentation is working with those mails
* SoGo throws errors with this address:

> #!$%&'*+-/=?^_`{}|~@lab.it-schley.eu

> An error occurred during object publishing
> tried to access private object (0x0x564e586c2a80, SoClass=SOGoMailAccounts)
* SoGo logout doesn't work either
* Receiving mails is also not possible on this special address:

> NOQUEUE: reject: RCPT from mail.neuland.tech[163.172.125.60]: 454 4.7.1 <#!$%&'*+-/=?^_`{}|~@lab.it-schley.eu>: Relay access denied; from=<test@neuland.tech> to=<#!$%&'*+-/=?^_`{}|~@lab.it-schley.eu> proto=ESMTP helo=<mail.neuland.tech>


So far we can say, at least mailcow ui errors can be avoided but not all components support rfc 5322 mails.
