### ISSUE TITLE
Sogo vacation and 550 5.7.1 dmark issues

### ISSUE THREAD

**Issue by kilo42L** [mailcow/mailcow-dockerized#1662]
Hello,  we have just noticed that when a user has setup a vacation responder via SOGo that specifically Yahoo and Gmail will not accept the immediate vacation reply and I get these errors in my postfix logs

3019218337A: to=<myemail@gmail.com>, relay=gmail-smtp-in.l.google.com[108.177.122.27]:25, delay=2.9, delays=0.18/0.05/2.4/0.28, dsn=5.7.1, status=bounced (host gmail-smtp-in.l.google.com[108.177.122.27] said: 550-5.7.1 Unauthenticated email from forestproperties.com is not accepted due to 550-5.7.1 domain's DMARC policy. Please contact the administrator of 550-5.7.1 forestproperties.com domain if this was a legitimate mail. Please 550-5.7.1 visit 550-5.7.1 https://support.google.com/mail/answer/2451690 to learn about the 550 5.7.1 DMARC initiative. b7-v6si3511933ywl.391 - gsmtp (in reply to end of DATA command)).

The person sending the email never gets the vacation message as it's blocked by Google, Yahoo.

I have setup everything according to instructions with the DNS.
The domain is Forest properties.com
Thanks for any help

**Comment by mkuron** [comment]
It seems like the Sieve-generated messages was not passed through the DKIM signer. I thought that was fixed a while ago, @andryyy?

@kilo42l, can you show us the full headers of such an autoresponse message?

**Comment by andryyy** [comment]
Now it is. I think I only thought about adding it but never did.

**Comment by kilo42L** [comment]
Thanks again andryyy I still have the message headers if you need them.
Also, when will this be live?  Can I just do an update?

**Comment by gino** [comment]
Seem to have this issue as well. I've added an alias for noreply@domain.com and created a filter in SOGo to send a rejection message back. :/

**Comment by andryyy** [comment]
@kilo42L Just saw I never answered you, sorry.

@Gino I don't see a problem:

![grafik](https://user-images.githubusercontent.com/2972950/51669445-cb843100-1fc4-11e9-910d-d2b681add0b5.png)

What exactly is happening?

**Comment by gino** [comment]
@andryyy 
I just created an alias called `noreply@test.com` that forwards to my `personal@test.com`. In SOGo I created a filter, that it should send a reject message and remove the message if it was sent to `noreply@test.com`. Whenever I take a look at the logs, I get the same error as in this issue:

```
Unauthenticated email from test.com is not accepted due to 550-5.7.1 domain's DMARC policy. Please contact the administrator of 550-5.7.1 test.com domain if this was a legitimate mail. 
```
