### ISSUE TITLE
lookup error for DNS query

### ISSUE THREAD

**Issue by Grosslukass** [mailcow/mailcow-dockerized#1782]
About 3 weeks ago I set up a mailcow-dockerized mailserver. Everything worked fine until now.

Since 2 days I'm not able to send or receive any emails from or to a different domain, that isn't mine.
I'm able to send a mail from example@mydomain.com to example@mydomain.com.

When I send a mail from example@mydomain.com to example@web.de or to example@gmail.com the e-mail is sent, but it doesn't arrive.
Same when I send a mail from example@web.de or example@gmail.com to example@mydomain.com. It doesn't arrive.

Postfix log says:

> NOQUEUE: reject: RCPT from unknown[217.XXX.XXX.XXX]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [217.XXX.XXX.XXX]; from=<example@web.de> to=<example@mydomain.de> proto=ESMTP helo=<mout.web.de>

> warning: dnsblog_query: lookup error for DNS query 78.XXX.XXX.XXX.zen.spamhaus.org: Host or domain name not found. Name service error for name=78.XXX.XXX.XXX.zen.spamhaus.org type=A: Host not found, try again
warning: dnsblog_query: lookup error for DNS query 78.XXX.XXX.XXX.bl.mailspike.net: Host or domain name not found. Name service error for name=78.XXX.XXX.XXX.bl.mailspike.net type=A: Host not found, try again

> 8491B2267F: to=<example@web.de>, relay=none, delay=11458, delays=11448/10/0/0.02, dsn=4.4.3, status=deferred (delivery temporarily suspended: Host or domain name not found. Name service error for name=web.de type=MX: Host not found, try again)

ACME logs:

> 19.9.2018, 18:24:25	Use SKIP LETS ENCRYPT=y in mailcow.conf to skip it permanently.
19.9.2018, 18:24:25	Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
19.9.2018, 18:24:25	Cannot match your IP against hostname mail.diealltagshirten.de ( connection timed out no servers could be reached)
19.9.2018, 18:24:25	Found A record for mail.diealltagshirten.de: connection timed out no servers could be reached
19.9.2018, 18:23:55	Cannot match your IP against hostname autodiscover.diealltagshirten.de ( connection timed out no servers could be reached)
19.9.2018, 18:23:55	Found A record for autodiscover.diealltagshirten.de: connection timed out no servers could be reached
19.9.2018, 18:23:25	Cannot match your IP against hostname autoconfig.diealltagshirten.de ( connection timed out no servers could be reached)
19.9.2018, 18:23:25	Found A record for autoconfig.diealltagshirten.de: connection timed out no servers could be reached
19.9.2018, 18:22:55	OK
19.9.2018, 18:22:55	Waiting for domain table...
19.9.2018, 18:22:42	OK
19.9.2018, 18:20:43	Detecting IP addresses...
19.9.2018, 18:20:43	Initializing, please wait...
19.9.2018, 18:20:43	Waiting for database...
19.9.2018, 18:20:43	OK
19.9.2018, 18:20:43	Waiting for Docker API...

My /etc/resolv.conf:

> nameserver 8.8.8.8
nameserver 8.8.4.4

- nslookup web.de - works
- nslookup web.de 127.0.0.11 - doesn't work (;; connection timed out; no servers could be reached
)
- docker-compose exec unbound-mailcow nslookup web.de - works
- docker-compose exec unbound-mailcow nslookup google.com - works
- docker-compose exec unbound-mailcow nslookup web.de 127.0.0.11 - works

My DNS-entries:

Hostname | type | adress
------------ | -------------  | -------------
autoconfig | CNAME | 5.XXX.XXX.XXX
autodiscover | CNAME | 5.XXX.XXX.XXX
 _ | MX | mydomain.com
 _ | SPF | mydomain.com
 _ | A | 5.XXX.XXX.XXX
mail | A | 5.XXX.XXX.XXX
www | A | 5.XXX.XXX.XXX

**Comment by mkuron** [comment]
This sounds like either the unbound container isn’t working (can you post its logs?) or you have a firewall configured that inadvertently blocks access to it.

**Comment by Grosslukass** [comment]
During the installation, I have released all the required ports.

The unbound logs:

> unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1537325232] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1537325232] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1537325232] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1537325234] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1537327925] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1537327925] unbound[1:0] info: server stats for thread 0: 510 queries, 0 answers from cache, 510 recu                                                                                                                rsions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1537327925] unbound[1:0] info: server stats for thread 0: requestlist max 18 avg 6.79216 exceeded 0 j                                                                                                                ostled 0
unbound-mailcow_1    | [1537327925] unbound[1:0] info: average recursion processing time 100.474693 sec
unbound-mailcow_1    | [1537327925] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1537327925] unbound[1:0] info: [25%]=36.044 median[50%]=77.8182 [75%]=120.545
unbound-mailcow_1    | [1537327925] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1537327925] unbound[1:0] info:    0.131072    0.262144 1
unbound-mailcow_1    | [1537327925] unbound[1:0] info:    0.524288    1.000000 1
unbound-mailcow_1    | [1537327925] unbound[1:0] info:    1.000000    2.000000 1
unbound-mailcow_1    | [1537327925] unbound[1:0] info:    2.000000    4.000000 7
unbound-mailcow_1    | [1537327925] unbound[1:0] info:    4.000000    8.000000 13
unbound-mailcow_1    | [1537327925] unbound[1:0] info:    8.000000   16.000000 30
unbound-mailcow_1    | [1537327925] unbound[1:0] info:   16.000000   32.000000 53
unbound-mailcow_1    | [1537327925] unbound[1:0] info:   32.000000   64.000000 91
unbound-mailcow_1    | [1537327925] unbound[1:0] info:   64.000000  128.000000 176
unbound-mailcow_1    | [1537327925] unbound[1:0] info:  128.000000  256.000000 57
unbound-mailcow_1    | [1537327925] unbound[1:0] info:  256.000000  512.000000 40
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
-=O#- #  #    #
unbound-mailcow_1    | curl: (6) Could not resolve host: www.internic.net
unbound-mailcow_1    | [1537328057] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1537328057] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1537328057] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1537328059] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1537329265] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1537329265] unbound[1:0] info: server stats for thread 0: 274 queries, 0 answers from cache, 274 recu                                                                                                                rsions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1537329265] unbound[1:0] info: server stats for thread 0: requestlist max 13 avg 7.94161 exceeded 0 j                                                                                                                ostled 0
unbound-mailcow_1    | [1537329265] unbound[1:0] info: average recursion processing time 70.489483 sec
unbound-mailcow_1    | [1537329265] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1537329265] unbound[1:0] info: [25%]=17.9592 median[50%]=41.7143 [75%]=110.345
unbound-mailcow_1    | [1537329265] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    0.032768    0.065536 2
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    0.065536    0.131072 1
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    0.524288    1.000000 2
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    1.000000    2.000000 7
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    2.000000    4.000000 3
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    4.000000    8.000000 14
unbound-mailcow_1    | [1537329265] unbound[1:0] info:    8.000000   16.000000 25
unbound-mailcow_1    | [1537329265] unbound[1:0] info:   16.000000   32.000000 49
unbound-mailcow_1    | [1537329265] unbound[1:0] info:   32.000000   64.000000 56
unbound-mailcow_1    | [1537329265] unbound[1:0] info:   64.000000  128.000000 29
unbound-mailcow_1    | [1537329265] unbound[1:0] info:  128.000000  256.000000 41
unbound-mailcow_1    | [1537329265] unbound[1:0] info:  256.000000  512.000000 11
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1537329399] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1537329399] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1537329399] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1537329401] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1537331530] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1537331530] unbound[1:0] info: server stats for thread 0: 418 queries, 0 answers from cache, 418 recu                                                                                                                rsions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1537331530] unbound[1:0] info: server stats for thread 0: requestlist max 12 avg 6.13636 exceeded 0 j                                                                                                                ostled 0
unbound-mailcow_1    | [1537331530] unbound[1:0] info: average recursion processing time 107.623396 sec
unbound-mailcow_1    | [1537331530] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1537331530] unbound[1:0] info: [25%]=25.6875 median[50%]=59.3488 [75%]=168.216
unbound-mailcow_1    | [1537331530] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1537331530] unbound[1:0] info:    0.131072    0.262144 1
unbound-mailcow_1    | [1537331530] unbound[1:0] info:    1.000000    2.000000 3
unbound-mailcow_1    | [1537331530] unbound[1:0] info:    2.000000    4.000000 12
unbound-mailcow_1    | [1537331530] unbound[1:0] info:    4.000000    8.000000 21
unbound-mailcow_1    | [1537331530] unbound[1:0] info:    8.000000   16.000000 23
unbound-mailcow_1    | [1537331530] unbound[1:0] info:   16.000000   32.000000 64
unbound-mailcow_1    | [1537331530] unbound[1:0] info:   32.000000   64.000000 86
unbound-mailcow_1    | [1537331530] unbound[1:0] info:   64.000000  128.000000 63
unbound-mailcow_1    | [1537331530] unbound[1:0] info:  128.000000  256.000000 74
unbound-mailcow_1    | [1537331530] unbound[1:0] info:  256.000000  512.000000 48
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1537331655] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1537331655] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1537331655] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1537331657] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1537361751] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1537361751] unbound[1:0] info: server stats for thread 0: 3535 queries, 1768 answers from cache, 1767                                                                                                                 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1537361751] unbound[1:0] info: server stats for thread 0: requestlist max 9 avg 1.13865 exceeded 0 jo                                                                                                                stled 0
unbound-mailcow_1    | [1537361751] unbound[1:0] info: average recursion processing time 40.117691 sec
unbound-mailcow_1    | [1537361751] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1537361751] unbound[1:0] info: [25%]=4.18324e-07 median[50%]=8.36648e-07 [75%]=71.7037
unbound-mailcow_1    | [1537361751] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    0.000000    0.000001 1056
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    0.065536    0.131072 1
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    0.262144    0.524288 1
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    0.524288    1.000000 2
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    1.000000    2.000000 1
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    2.000000    4.000000 5
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    4.000000    8.000000 10
unbound-mailcow_1    | [1537361751] unbound[1:0] info:    8.000000   16.000000 26
unbound-mailcow_1    | [1537361751] unbound[1:0] info:   16.000000   32.000000 41
unbound-mailcow_1    | [1537361751] unbound[1:0] info:   32.000000   64.000000 140
unbound-mailcow_1    | [1537361751] unbound[1:0] info:   64.000000  128.000000 351
unbound-mailcow_1    | [1537361751] unbound[1:0] info:  128.000000  256.000000 133
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1537361850] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1537361850] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1537361852] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1537362458] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1537362458] unbound[1:0] info: server stats for thread 0: 225 queries, 0 answers from cache, 225 recu                                                                                                                rsions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1537362458] unbound[1:0] info: server stats for thread 0: requestlist max 19 avg 10.8889 exceeded 0 j                                                                                                                ostled 0
unbound-mailcow_1    | [1537362458] unbound[1:0] info: average recursion processing time 64.044177 sec
unbound-mailcow_1    | [1537362458] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1537362458] unbound[1:0] info: [25%]=22.1905 median[50%]=49.7455 [75%]=112.381
unbound-mailcow_1    | [1537362458] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1537362458] unbound[1:0] info:    1.000000    2.000000 1
unbound-mailcow_1    | [1537362458] unbound[1:0] info:    2.000000    4.000000 5
unbound-mailcow_1    | [1537362458] unbound[1:0] info:    4.000000    8.000000 15
unbound-mailcow_1    | [1537362458] unbound[1:0] info:    8.000000   16.000000 19
unbound-mailcow_1    | [1537362458] unbound[1:0] info:   16.000000   32.000000 42
unbound-mailcow_1    | [1537362458] unbound[1:0] info:   32.000000   64.000000 55
unbound-mailcow_1    | [1537362458] unbound[1:0] info:   64.000000  128.000000 42
unbound-mailcow_1    | [1537362458] unbound[1:0] info:  128.000000  256.000000 46
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1537362593] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1537362593] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1537362595] unbound[1:0] info: start of service (unbound 1.6.2).

**Comment by mkuron** [comment]
> I have released all the required ports

What do you mean when you say that? If you have a host firewall, opening ports is often not enough in a Docker environment. Disable the firewall and reboot, then check whether the issue persists.

**Comment by Grosslukass** [comment]
Sorry, I mean that I opened all the ports.
Disabled the firewall and rebooted, but the problem still persists. Same errors in log.

**Comment by Grosslukass** [comment]
The problem is still not resolved.
Are there any other ways to find the cause of the error?

Atm, I have these postfix errors (with disabled firewall):

> 51EF21FA2B: to=<example@web.de>, relay=none, delay=483, delays=473/0.07/10/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=web.de type=MX: Host not found, try again)

> NOQUEUE: reject: RCPT from unknown[217.XXX.XXX.XXX]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [217.XXX.XXX.XXX]; from=<example@web.de> to=<exmaple@mydomain.de> proto=ESMTP helo=<mout.web.de>

> warning: dnsblog_query: lookup error for DNS query 78.XXX.XXX.XXX.zen.spamhaus.org: Host or domain name not found. Name service error for name=78.XXX.XXX.XXX.zen.spamhaus.org type=A: Host not found, try again
warning	warning: dnsblog_query: lookup error for DNS query 78.XXX.XXX.XXX.bl.mailspike.net: Host or domain name not found. Name service error for name=78.XXX.XXX.XXX.bl.mailspike.net type=A: Host not found, try again

**Comment by Skydiver84de** [comment]
now i have the exact same problem! There is **no** more email coming through, because unbound cannot resolve any hostname like 154.132.68.51.dnsbl.sorbs.net

Normal lookups work within the unbound container.

Tried to rebuild the container, no changes.

ANY IDEA?!

**Comment by andryyy** [comment]
What do you mean with "Normal lookups work within the unbound container."?

What did you try exactly so far?

What's in unbound-mailcow logs?

**Comment by Skydiver84de** [comment]
docker-compose exec unbound-mailcow nslookup web.de - works
docker-compose exec unbound-mailcow nslookup 154.132.68.51.dnsbl.sorbs.net - did not work (could not be resolved)

Unbound logs showed the same than Grosslukass logs (nothing).

Rebuild the unbound-mailcow container - restarted - no change.

Restarted the whole server - WORKS again.

I have no clue ?!

**Comment by andryyy** [comment]
Unbound does not use itself to lookup DNS. :-)

**Comment by Skydiver84de** [comment]
so the really problem was the dns system of the host? maybe caused by an update?

**Comment by andryyy** [comment]
Not sure. Could be a firewall (if any) or unbound-mailcow itself.

**Comment by mvanduijker** [comment]
Same problem here `docker-compose restart` solved it for me. 

Strange thing is, in the web interface where you can check if your dns is setup correctly, it was giving me an error for the PTR record. After restart the PTR record check was green again.

**Comment by SvenWen** [comment]
I actually had the same issue this morning. Mailcow was not able to resolve the IP addresses of the mail recipients (@web.de, @microsoft.com or whatsoever). Furthermore, incoming mails were not delivered into the mailboxes.

After restarting the server, everything is back to normal.

**Comment by andryyy** [comment]
Could be due to an old anchor. It should be enough to restart unbound-mailcow in that case.

**Comment by SvenWen** [comment]
Actually, postfix was giving hundreds of warning messages. I just realized that something is wrong, because no external messages were coming in.

Would there be a way to have mailcow automatically forward such warning messages to the admin? Now, one would always have to log into the server and check logs. Honestly, since mailcow is usually running fine, I don’t do that every day.

**Comment by constin** [comment]
had today same problem on one server.

**Comment by toffelwurst** [comment]
Had the same issue, probably linked to ICANNs Root-Key rollover yesterday.
Rebooting the unbound container fixed it for me.

**Comment by markirb** [comment]
Same here yesterday. Restarting unbound fixed it. Could such an error be detected by watchdog and do this automatically?

**Comment by andryyy** [comment]
Yes, I plan to add it.

**Comment by MarkOnDuty** [comment]
This hit me as well. Same symptoms. That warm pride that accompanies getting a bunch of work done was the first sign that email was bunged up.

Disabling reject_unknown_reverse_client_hostname in Postfix's config and restarting all the containers got email flowing again. Looks like the restart is actually what fixed it, so I've enabled the reverse client hostname check again. If the problem reappears, I'll report back.

**Comment by MAGICCC** [comment]
It was due to the DNSSEC root key rollover https://www.redhat.com/en/blog/what-you-need-know-about-first-ever-dnssec-root-key-rollover-october-11-2018
Just restart/update unbound container

**Comment by markirb** [comment]
after reading the redhat-article, the reason is clear, but also the article states that 
> Properly working software should have already picked up this new key.

so what is the exact reason that undound is not working properly here?
so we are prepared for the next rollover?

**Comment by MAGICCC** [comment]
Afaik unbound wasn't on the latest version when the rollover was in action, but now it is

**Comment by mkuron** [comment]
It was this issue, fixed in unbound 1.6.5: 
https://www.unbound.net/root-11sep-11oct.html
