### ISSUE TITLE
Invalid interpolation format for "ports" option in service "postfix-mailcow": "${SMTP_PORT:-25}:25"

### ISSUE THREAD

**Issue by neilgee** [mailcow/mailcow-dockerized#246]
On install when using `docker-compose-pull` getting error...
```
root@wp-beaches-dallas-mail:~/mailcow-dockerized# docker-compose pull
ERROR: Invalid interpolation format for "ports" option in service "postfix-mailcow": "${SMTP_PORT:-25}:25"
```
There is some reference in the mailcow docs..

> You may need to stop an existing pre-installed MTA which blocks port 25/tcp. See this chapter to learn how to reconfigure Postfix to run besides mailcow after a successful installation.

But the link referenced is dead - https://andryyy.github.io/mailcow-dockerized/first_steps/#install-a-local-mta

**Comment by mkuron** [comment]
Is your docker-compose version up to date?

**Comment by neilgee** [comment]
Odd I have 1.8.0 but see 1.13 is the latest - I can't seem to update it 

tried - as per https://github.com/docker/compose/releases
```
curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

but still get
```
root@wp-beaches-dallas-mail:~/mailcow-dockerized# docker-compose -v
docker-compose version 1.8.0, build unknown
```

**Comment by mkuron** [comment]
Do `which -a docker-compose` to check whether you have an older copy somewhere else in your `$PATH`.

**Comment by neilgee** [comment]
Yes you are right I had 2
```
root@wp-beaches-dallas-mail:~/mailcow-dockerized# which -a docker-compose
/usr/local/bin/docker-compose
/usr/bin/docker-compose
```
established the `/usr/bin/docker-compose` was the older one and removed it and refreshed the shell - but when I do a version command now it still looks in the wrong directory...

```
root@wp-beaches-dallas-mail:~# docker-compose -v
-bash: /usr/bin/docker-compose: No such file or directory
```
I am using Ubuntu 16.04

**Comment by mkuron** [comment]
`hash -r` or logging out and back in should fix that.

**Comment by neilgee** [comment]
ok great thanks, now have the latest version but still get the original error...

```
root@wp-beaches-dallas-mail:~/mailcow-dockerized# which -a docker-compose
/usr/local/bin/docker-compose
root@wp-beaches-dallas-mail:~/mailcow-dockerized# docker-compose --version
docker-compose version 1.13.0, build 1719ceb
root@wp-beaches-dallas-mail:~/mailcow-dockerized# docker-compose pull
ERROR: Invalid interpolation format for "ports" option in service "postfix-mailcow": "${SMTP_PORT:-25}:25"
```

I have a `serverpilot` instance https://serverpilot.io/ on the server which must be interfering with the install.

**Comment by AlJohri** [comment]
I'm getting this same error using the port option in this way on a separate app.

**Comment by devfaz** [comment]
Solved this by re-adding 

version: "2.3"

I removed the ".3" after docker-compose complained about this. I had an old verison of docker-compose and it looks like newer versions are not complaining about version "2.3" and version "2.3" is required by this new version to handle the ports-sections correctly.

**Comment by andryyy** [comment]
The update script pulls a new compose version.
