### ISSUE TITLE
API - ratelimit

### ISSUE THREAD

**Issue by pantunes87** [mailcow/mailcow-dockerized#4368]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [*] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [*] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [*] I have understood that answers are voluntary and community-driven, and not commercial support.
- [*] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Hi all. I’m trying to create/change the rate limit through API, and the log seems ok but the rate limit change to disable.. example before and after:

**BEFORE:**

curl -s -X ‘GET’ ‘https://mail.domain.com/api/v1/get/rl-mbox/user1%40domain.com’ -H ‘accept: application/json’ -H ‘X-API-Key: XXXXXXXXXXX | jq ’.'
{
“value”: “10”,
“frame”: “s”

**CHANGING:**

curl -s -X ‘POST’ ‘https://mail.domain.com/api/v1/edit/rl-mbox/’ -H ‘accept: application/json’ -H ‘Content-Type: application/json’ -H ‘X-API-Key: XXXXXXXXXXXXXX’ -d '{
“attr”: {
“rl_vlaue”: “30”,
“rl_frame”: “m”
},
“items”: [
“user1@domain.com”
]
}‘ | jq ’.'
[
{
“type”: “success”,
“log”: [
“ratelimit”,
“edit”,
“mailbox”,
{
“object”: [
“user1@domain.com”
],
“rl_vlaue”: “30”,
“rl_frame”: “m”
}
],
“msg”: [
“rl_saved”,
“user1@domain.com”
]
}
]

**AFTER:**

curl -s -X ‘GET’ ‘https://mail.domain.com/api/v1/get/rl-mbox/mail.domain.com%40domain.com’ -H ‘accept: application/json’ -H ‘X-API-Key: XXXXXXXX’ | jq ‘.’

**Comment by dragoangel** [comment]
Doublechecked - issue reproduced

**Comment by dragoangel** [comment]
Well actually edit user acl api also do not work :(, maybe something else... need to recheck stuff

**Comment by pantunes87** [comment]
Hi, 

Do you have an estimated date to deliver a fix?

Regards,
Pedro Antunes

**Comment by ntimo** [comment]
Fixed in https://github.com/mailcow/mailcow-dockerized/commit/c82f38a025c3e93630744ca9ab46da5a1dfbd6e4

**Comment by pantunes87** [comment]
Can you please reopen the ticket? This issue is not solved. I can't apply via API. 

When I apply RT, API returns successm but the change is not applied.

**Comment by MAGICCC** [comment]
Its not in master, only in staging. Either you apply the patch yourself or wait until the next release - prob in February

**Comment by pantunes87** [comment]
ok :) thanks
