### ISSUE TITLE
SOGo 501 error due to MariaDB NoMoreConnections

### ISSUE THREAD

**Issue by benoitjpnet** [mailcow/mailcow-dockerized#4374]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Synchronization error on my Android device with DAVx5:
![Screenshot_20211211-123301](https://user-images.githubusercontent.com/1057913/145662358-ccc36bbb-37b0-4063-b0b8-5d8f7f576362.jpg)

## Logs

```
php-fpm-mailcow_1    | 172.22.1.10 - xxx@benpro.fr 11/Dec/2021:03:29:21 +0000 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - xxx@benpro.fr [11/Dec/2021:03:29:21 +0000] "GET /sogo-auth HTTP/1.0" 200 0 "-" "DAVx5/3.3.12-ose (2021/07/21; dav4jvm; okhttp/4.9.1) Android/11"
nginx-mailcow_1      | 45.8.223.212 - xxx@benpro.fr [11/Dec/2021:03:29:21 +0000] "PROPFIND /SOGo/dav/xxx@benpro.fr/Contacts/personal/ HTTP/2.0" 501 0 "-" "DAVx5/3.3.12-ose (2021/07/21; dav4jvm; okhttp/4.9.1) Android/11"
sogo-mailcow_1       | Dec 11 03:29:21 f79a784b8278 2021-12-11 03:29:21.512 sogod[69:69] EXCEPTION: <MySQL4CouldNotOpenChannelException: 0x55dfeb7883e0> NAME:NoMoreConnections REASON:cannot open a additional connection ! INFO:(null)
sogo-mailcow_1       | Dec 11 03:29:21 f79a784b8278 sogod [69]: 45.8.223.212 "PROPFIND /SOGo/dav/xxx@benpro.fr/Contacts/personal/ HTTP/1.0" 501 0/296 0.001 - - 0 - 162

```

Looks like issue with MariaDB max connections.
Strangely enough, recently the limit was increased by 25cecf5f9d05f3d9da62a8e91362438956a33d12.

## Reproduction

Mailcow + SOGo and contacts/calendar sync on Android. 

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.3 LTS |
| Is Apparmor, SELinux or similar active? | apparmor module is loaded. |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2G, 2vCPU |
| Docker Version (`docker version`) | 20.10.11 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by benoitjpnet** [comment]
Problem disappear after a restart of `mailcowdockerized_mysql-mailcow_1`. Will try to get more information within MariaDB shell when the issue hit back.

**Comment by dragoangel** [comment]
This known bug already reported to sogo, and this upstream - bugs in upstream should be reported to upstream

**Comment by dragoangel** [comment]
P.s. your ram amount is out of supported setup.

**Comment by benoitjpnet** [comment]
2G of RAM with 2G of SWAP is fine without Clamd and Solr.
Server and mailcow are working fine since August 2020. :)

Could you link upstream bug?

**Comment by dragoangel** [comment]
@andryyy do you have link to the bug in sogo bug tracker? Is there any updates?

**Comment by MAGICCC** [comment]
Since mailcow is using 5.4.0 now, maybe they patched the issue?

**Comment by dragoangel** [comment]
@MAGICCC do not see anything related to it in changelog. I will update and see, but I don't think issue was being solved

**Comment by jt0in3e** [comment]
don't know whether it is the same issue but I'm also facing 501 Error while trying to access SOGo in a browser. 

from logs `docker-compose logs | egrep -i sogo` there are only this:

```
sogo-mailcow_1 | Sep 24 13:12:27 589976464d0f 2021-09-24 13:12:27.027 sogod[66:66] EXCEPTION: <NSException: 0×559cc2d44aa0> NAME:SOGoDefaultsSourceUnmutableSource REASON:UserDefaults source ‘{SOGoMailDomain = “example.eu”; SOGoUserSources = ({DomainFieldName = domain; KindFieldName = kind; MailFieldNames = (aliases, “ad_aliases”, “ext_acl”); MultipleBookingsFieldName = “multiple_bookings”; canAuthenticate = YES; displayName = “GAL example.eu”; id = “example.eu”; isAddressBook = YES; listRequiresDot = NO; prependPasswordScheme = YES; type = sql; userPasswordAlgorithm = “BLF-CRYPT”; viewURL = “mysql://mailcow:31tv826v2moaw152d15ecb30bb826fdc6e827313ac2589cf000539e59z313v644444var%2Frun%2Fmysqld%2Fmysqld.sock/mailcow/_sogo_static_view”; }); }’ is not mutable INFO : ( null)

sogo-mailcow_1 | Sep 24 13:12:27 589976464d0f sogod [66]: mailcowdockerized_watchdog-mailcow_1.mailcowdockerized_mailcow-network “GET /SOGo.index/ HTTP/1.1” 501 0/0 0.034 - - 0M - 10
```

everithing else works as expected.

**Comment by dragoangel** [comment]
Yes, GAL is broken over carddav :( and maybe it's related to issue with sql as well.

P.s. you need hide your password from connection string

**Comment by dragoangel** [comment]
issue solved by https://www.sogo.nu/bugs/view.php?id=4896

**Comment by jt0in3e** [comment]
> issue solved by https://www.sogo.nu/bugs/view.php?id=4896

@dragoangel Unfortunatelly there's still 501 Error in mine server. I've run ./update.sh. but it still the same

**Comment by dragoangel** [comment]
@jt0in3e your 501 is not related to this issue.

**Comment by dragoangel** [comment]
> don't know whether it is the same issue but I'm also facing 501 Error while trying to access SOGo in a browser. 
> 
> from logs `docker-compose logs | egrep -i sogo` there are only this:
> 
> ```
> sogo-mailcow_1 | Sep 24 13:12:27 589976464d0f 2021-09-24 13:12:27.027 sogod[66:66] EXCEPTION: <NSException: 0×559cc2d44aa0> NAME:SOGoDefaultsSourceUnmutableSource REASON:UserDefaults source ‘{SOGoMailDomain = “example.eu”; SOGoUserSources = ({DomainFieldName = domain; KindFieldName = kind; MailFieldNames = (aliases, “ad_aliases”, “ext_acl”); MultipleBookingsFieldName = “multiple_bookings”; canAuthenticate = YES; displayName = “GAL example.eu”; id = “example.eu”; isAddressBook = YES; listRequiresDot = NO; prependPasswordScheme = YES; type = sql; userPasswordAlgorithm = “BLF-CRYPT”; viewURL = “mysql://mailcow:31tv826v2moaw152d15ecb30bb826fdc6e827313ac2589cf000539e59z313v644444var%2Frun%2Fmysqld%2Fmysqld.sock/mailcow/_sogo_static_view”; }); }’ is not mutable INFO : ( null)
> 
> sogo-mailcow_1 | Sep 24 13:12:27 589976464d0f sogod [66]: mailcowdockerized_watchdog-mailcow_1.mailcowdockerized_mailcow-network “GET /SOGo.index/ HTTP/1.1” 501 0/0 0.034 - - 0M - 10
> ```
> 
> everithing else works as expected. 
> 
> 

You need provide more details, in telegram channel for example. I don't see any issues on 5.5.0.

**Comment by jt0in3e** [comment]
> > don't know whether it is the same issue but I'm also facing 501 Error while trying to access SOGo in a browser.
> > from logs `docker-compose logs | egrep -i sogo` there are only this:
> > ```
> > sogo-mailcow_1 | Sep 24 13:12:27 589976464d0f 2021-09-24 13:12:27.027 sogod[66:66] EXCEPTION: <NSException: 0×559cc2d44aa0> NAME:SOGoDefaultsSourceUnmutableSource REASON:UserDefaults source ‘{SOGoMailDomain = “example.eu”; SOGoUserSources = ({DomainFieldName = domain; KindFieldName = kind; MailFieldNames = (aliases, “ad_aliases”, “ext_acl”); MultipleBookingsFieldName = “multiple_bookings”; canAuthenticate = YES; displayName = “GAL example.eu”; id = “example.eu”; isAddressBook = YES; listRequiresDot = NO; prependPasswordScheme = YES; type = sql; userPasswordAlgorithm = “BLF-CRYPT”; viewURL = “mysql://mailcow:31tv826v2moaw152d15ecb30bb826fdc6e827313ac2589cf000539e59z313v644444var%2Frun%2Fmysqld%2Fmysqld.sock/mailcow/_sogo_static_view”; }); }’ is not mutable INFO : ( null)
> > 
> > sogo-mailcow_1 | Sep 24 13:12:27 589976464d0f sogod [66]: mailcowdockerized_watchdog-mailcow_1.mailcowdockerized_mailcow-network “GET /SOGo.index/ HTTP/1.1” 501 0/0 0.034 - - 0M - 10
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > everithing else works as expected.
> 
> You need provide more details, in telegram channel for example. I don't see any issues on 5.5.0.

Yes, thanks for your input. Have no possibility to trace the logs and to check everything. But will do and will come back when have results. 

p.s. I personally don't use Telegram, I think it is not a good idea to use it at all

**Comment by dragoangel** [comment]
@jt0in3e then use forum

p.s. you exposed your mysql password 😵‍💫

**Comment by jt0in3e** [comment]
> @jt0in3e then use forum
> 
> p.s. you exposed your mysql password face_with_spiral_eyes

@dragoangel thanks for pointing, but I've changed it completely prior posting )
