### ISSUE TITLE
docker-entrypoint.sh permissions issues

### ISSUE THREAD

**Issue by laymonk** [mailcow/mailcow-dockerized#580]
Trying to install mailcow-dockerized .. and repeatedly hitting the following error messages in the logs .. just after the mysql container has started .. 

```
mysql-mailcow_1      | 2017-09-11T21:55:57.027225154Z error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
mysql-mailcow_1      | 2017-09-11T21:55:58.016059062Z error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
mysql-mailcow_1      | 2017-09-11T21:55:59.058174253Z error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
mysql-mailcow_1      | 2017-09-11T21:56:00.284862620Z error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
mysql-mailcow_1      | 2017-09-11T21:56:01.956124542Z error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
```

* The system then hangs and does nothing forever .. and just keeps logging the same error message
* I would then clean up with ctrl-c followed by `docker-compose down -v --remove-orphans` .. 
* I have done a find on the host and chmoded all instances of docker-entrypoint.sh with:
```
find / -name docker-entrypoint.sh -ls 2>/dev/null | awk '{print $11}' | xargs chmod 777
```

* The files were 755 and now all these files are 777 .. but still mysql_mailcow does not seem to start up well .. 
* This is a mailcow image pulled down within the last hour .. via 
```
git clone https://github.com/mailcow/mailcow-dockerized && cd mailcow-dockerized
```

**Other notable conditions:**
* I am running in an ubuntu 16.04 lxd container
* have disabled ipv6 (because of #316) 
* I have also disabled clamav (even commented it out in docker-compose.yml because the mailcow.conf setting was being ignored)
* On the host (ie, within the lxd container), there is actually no /usr/local/bin/docker-entrypoint.sh, but find can see it within the docker images.  Trying to enter the mysql_mailcow docker container throws up an error
```
# docker exec -it 5c25aae2b0d4 bash
Error response from daemon: Container 5c25aae2b0d43d3c80edf7656461cd39d83f3799f09c830aa0f688211898911e is restarting, wait until the container is running
``` 

Any ideas what is happening here? .. a bug in an image, perhaps ?

**Comment by laymonk** [comment]
* Just tried to start over .. by moving out the old tree, and cloning mailcow repo again.  This time I get the following message while cloning the mailcow repo.
```
ERROR: manifest for mailcow/acme:1.16 not found
```
* carrying on with a `docker-compose up -d` throws up the same errors about docker-entrypoint.sh permissions on mysql_mailcow .. the error about missing acme manifest just meant the container got rebuilt as docker-compose started up.
* I can confirm now though that clamav is indeed being skipped as configured in mailcow.conf
* Will wait and try again tomorrow ..

**Comment by laymonk** [comment]
**More info**

* The logs suggest that clamav is being skipped
```
clamd-mailcow_1      | 2017-09-11T23:04:06.108221513Z SKIP_CLAMD=y, skipping ClamAV...
clamd-mailcow_1      | 2017-09-11T23:05:06.634994304Z SKIP_CLAMD=y, skipping ClamAV...
clamd-mailcow_1      | 2017-09-11T23:06:07.167601597Z SKIP_CLAMD=y, skipping ClamAV...
clamd-mailcow_1      | 2017-09-11T23:07:07.691887948Z SKIP_CLAMD=y, skipping ClamAV...
clamd-mailcow_1      | 2017-09-11T23:08:08.195672110Z SKIP_CLAMD=y, skipping ClamAV...
clamd-mailcow_1      | 2017-09-11T23:09:08.679160795Z SKIP_CLAMD=y, skipping ClamAV...
```

* But repeated docker ps shows both the mysql and clamd containers restarting endlessly .. 

```
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS               NAMES
3caf3f2fe385        mariadb:10.1        "docker-entrypoint..."   22 minutes ago      Restarting (1) 37 seconds ago                       mailcowdockerized_mysql-mailcow_1
2f767195d75e        mailcow/clamd:1.2   "/bootstrap.sh"          22 minutes ago      Restarting (0) 46 seconds ago                       mailcowdockerized_clamd-mailcow_1
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS               NAMES
3caf3f2fe385        mariadb:10.1        "docker-entrypoint..."   22 minutes ago      Restarting (1) 55 seconds ago                       mailcowdockerized_mysql-mailcow_1
2f767195d75e        mailcow/clamd:1.2   "/bootstrap.sh"          22 minutes ago      Restarting (0) 4 seconds ago                        mailcowdockerized_clamd-mailcow_1
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS               NAMES
3caf3f2fe385        mariadb:10.1        "docker-entrypoint..."   22 minutes ago      Restarting (1) 13 seconds ago                       mailcowdockerized_mysql-mailcow_1
2f767195d75e        mailcow/clamd:1.2   "/bootstrap.sh"          22 minutes ago      Restarting (0) 23 seconds ago                       mailcowdockerized_clamd-mailcow_1
```

**Comment by andryyy** [comment]
The MySQL image is actually the official MariaDB image, that's strange.

But I fixed the ClamAV error + pushed acme 1.16.

**Comment by laymonk** [comment]
@andryyy, thanks for looking at this.  

Just tried again now, and the situation is still the same.  I wonder if I should change the 'restart' parameter and see what happens.  But then again that would mean an incomplete bootstrap for mariadb.

Are you able to reproduce this?

**Comment by andryyy** [comment]
Did you run `docker-compose up -d` to recreate the container after pulling the new docker-compose.yml?

Btw: You should not modify any container/images by searching the files on the host system. It will break things. Have you tried to remove all containers and images and start over?

**Comment by laymonk** [comment]
I reckon so  .. I started over, by git cloning a fresh tree, then docker-pulling .. here is the startup 
```
# docker-compose up -d
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
Creating volume "mailcowdockerized_crypt-vol-1" with default driver
Creating volume "mailcowdockerized_redis-vol-1" with default driver
Creating volume "mailcowdockerized_vmail-vol-1" with default driver
Creating volume "mailcowdockerized_postfix-vol-1" with default driver
Creating volume "mailcowdockerized_rspamd-vol-1" with default driver
Creating volume "mailcowdockerized_mysql-vol-1" with default driver
Creating volume "mailcowdockerized_dkim-vol-1" with default driver
Creating mailcowdockerized_clamd-mailcow_1 ...
Creating mailcowdockerized_mysql-mailcow_1 ...
Creating mailcowdockerized_clamd-mailcow_1
Creating mailcowdockerized_clamd-mailcow_1 ... done
```
It never gets beyond there .. and a peek in the logs confirms the same issue

**Comment by andryyy** [comment]
Hm, flying over some issues related to that @ moby, I wonder if you can fix it by adding a full path to the entrypoint in `docker-compose.yml`  for that service =>

```
....
    mysql-mailcow:
      image: mariadb:10.1
      entrypoint: /usr/local/bin/docker-entrypoint.sh
      ....
...
```

**Comment by laymonk** [comment]
Just tried this .. and it made no difference .. it just seems like the mysql image supplies no docker-entrypoint.sh file, but the bootstrap is trying to use one .. 

```
~/mailcow-dockerized/data/Dockerfiles# tree
.
├── acme
│   ├── Dockerfile
│   └── docker-entrypoint.sh
├── clamd
│   ├── Dockerfile
│   ├── bootstrap.sh
│   └── dl_files.sh
├── dovecot
│   ├── Dockerfile
│   ├── docker-entrypoint.sh
│   ├── imapsync
│   ├── imapsync_cron.pl
│   ├── postlogin.sh
│   ├── report-ham.sieve
│   ├── report-spam.sieve
│   ├── rspamd-pipe-ham
│   ├── rspamd-pipe-spam
│   ├── supervisord.conf
│   └── syslog-ng.conf
├── fail2ban
│   ├── Dockerfile
│   └── logwatch.py
├── memcached
├── mysql
├── nginx
├── phpfpm
│   ├── Dockerfile
│   └── docker-entrypoint.sh
├── postfix
│   ├── Dockerfile
│   ├── postfix.sh
│   ├── supervisord.conf
│   ├── syslog-ng.conf
│   ├── whitelist_forwardinghosts.sh
│   ├── zeyple.conf
│   └── zeyple.py
├── redis
├── rspamd
│   ├── Dockerfile
│   ├── docker-entrypoint.sh
│   ├── lua_util.lua
│   ├── ratelimit.lua
│   └── settings.conf
├── sogo
│   ├── Dockerfile
│   ├── bootstrap-sogo.sh
│   ├── supervisord.conf
│   └── syslog-ng.conf
└── unbound
    ├── Dockerfile
    └── docker-entrypoint.sh
```
* I am considering unpacking that mariadb image to look see ..

**Comment by andryyy** [comment]
The MySQL image is pulled from the official MariaDB Docker sources, we have not modified it. You can find the Dockerfile and script here: https://github.com/docker-library/mariadb/tree/master/10.2

Please also try to remove all downloaded Docker images after running "docker-compose down". I think you may have changed these images when you run the find command.

**Comment by laymonk** [comment]
* Well, I am not sure why having some files as 777 instead of 755 (and in response to already failing bootstrap) could be a factor.  
* But I have deleted all images, moved out the tree and started over.

**But still the very same issue**

* I was also already looking at those [official mariadb images](https://hub.docker.com/_/mariadb/) .. 
* Is there any special reason to stick with 10.1 in mailcow's docker-compose file, instead of the latest stable version (10.2)?  .. 
* Ironically, your last comment refers to mariadb:10.2 but mailcow docker-compose is using 10.1 
* was going to change to 10.2 .. but decided to check with you first 

Looking at the mariadb Dockerfile, the failure point is around here:
```
COPY docker-entrypoint.sh /usr/local/bin/
RUN ln -s usr/local/bin/docker-entrypoint.sh / # backwards compat
ENTRYPOINT ["docker-entrypoint.sh"]
```
* it just seems as if the COPY never happens or that the 'ln' command is referring to an object not created in the COPY command .. notice the '/' in the COPY is missing in the ln ..
* Do we even need this backward compact symlink ?

* I cannot think of anything else to try, besides changing to mariadb:10.2, but the dockerfiles are identical between 10.1 and 10.2
* It would help if you (or someone else) tried to reproduce this by just attempting a deployment of mailcow ..

**Comment by laymonk** [comment]
* I have been experimenting by running these images directly, outside mailcow:
```
docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=password -d mariadb:10.1
docker run --name some-mariadb2 -e MYSQL_ROOT_PASSWORD=password -d mariadb:10.2
docker run --name some-mariadb3 -e MYSQL_ROOT_PASSWORD=password -d mariadb:10.3
```
* and all of them are failing on this same issue .. So, the problem is definitely with the official mariadb images .. 
```
# docker container logs 1fd2257e2c41a6589401503902444d7f8a38ef4d88f5e12c73b4bed729181835
error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied
```
Did mailcow just start using mariadb recently?  Or I have just unearthed a previously unknown bug?

**Comment by andryyy** [comment]
I need to check the changes made in 10.2. 👍 Just think of all the stuff that was changed in MySQL 5.7. 

Moreover, this is a LXC issue. The image is already built and hosted on Docker hub, you never actually run what you see in the Dockerfile. So all comands are already run. You _can_ rebuild the image locally, but there is no need to, it will result in the same image as Docker hosts on its hub.

You find an issue related to this here => https://github.com/moby/moby/issues/34644

Have you tried the MySQL images instead of MariaDB? They are pretty much the same though...

**Comment by laymonk** [comment]
@andryyy .. thanks for all your support .. I have had to:
* try to docker run all mysql tags (latest, 5.6,5.7)
* even tried [bitnami/mariadb](https://hub.docker.com/r/bitnami/mariadb/) .. but hit a [post-install  issue](https://github.com/bitnami/bitnami-docker-drupal/issues/22)

**Bottomline, I just could not get any mysql version to run .. all failed to the same error**

* So, I then knew the issue was likely with lxd ..
* have since tracked this down to an lxd security setting which I was sure I set, because it's a known requirement for running docker within lxd.  
* But it seems I set it, rebooted the container (warm boot) and the setting was never really applied ..  I needed a cold boot, by having lxc restart the container .. the following command will confirm if it's set
```
lxc config get mailcow security.privilege
# if not set, set it with 
lxc config set mailcow security.privilege true
```
So, this setting was off .. and setting it to true has allowed me to get beyond that ..

Everything is now bootstrapping OK, except fail2ban .. which fails with:
```
Creating mailcowdockerized_fail2ban-mailcow_1 ... error

ERROR: for mailcowdockerized_fail2ban-mailcow_1  Cannot start service fail2ban-mailcow: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"process_linux.go:284: setting cgroup config for ready process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/b6b6f5748cc3fe28aa173c828958ae55989adb868e22c0117c7052fed7228640/devices.allow: operation not permitted\\\"\""
Creating mailcowdockerized_nginx-mailcow_1 ... done
Creating mailcowdockerized_rspamd-mailcow_1 ... 
Creating mailcowdockerized_acme-mailcow_1 ... 
Creating mailcowdockerized_acme-mailcow_1
Creating mailcowdockerized_rspamd-mailcow_1 ... done

ERROR: for fail2ban-mailcow  Cannot start service fail2ban-mailcow: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"process_linux.go:284: setting cgroup config for ready process caused \\\"failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/docker/b6b6f5748cc3fe28aa173c828958ae55989adb868e22c0117c7052fed7228640/devices.allow: operation not permitted\\\"\""

ERROR: Encountered errors while bringing up the project.
```

`setting cgroup config for ready process caused \\\"failed to write a *:* rwm to devices.allow` suggests this is an lxc oriented resource/security limit applied to containers .. 

Wondering if anyone else has reported a similar issue with fail2ban ?

**Comment by laymonk** [comment]
@andryyy, I am running now without fail2ban until I can get the issues resolved .. this problem with fail2ban is probably related to https://github.com/lxc/lxd/issues/2825 .. 

So, you can consider this issue resolved .. I have opened another issue about not being able to access the mailcowUI .. due to a sql error message .. #591

**Comment by andryyy** [comment]
It is a bug with your lxc installation. 

Im almost sure you will run in the same problem with other containers once they are started.
