### ISSUE TITLE
Issue with Let's encrypt

### ISSUE THREAD

**Issue by MoritzWeber0** [mailcow/mailcow-dockerized#754]
Hi, i have a problem with my mailcow docktorized installation. I get the error when I want to use let's encrypt:

`[{ "type": "urn:acme:error:malformed", "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]", "status": 400 }]`

How can i fix that? Is there a configuration file?

**Comment by w796933** [comment]
i have the some  error.   you can  fix it ?

**Comment by andryyy** [comment]
Give me a few minutes.

**Comment by w796933** [comment]
okay. so thanks .  nice day .

**Comment by jbiffis** [comment]
having the issue here as well.  Looks like LE updated their T&C, acme-client needs to update something on their end?

https://github.com/kristapsdz/acme-client-portable/issues/46

**Comment by andryyy** [comment]
“fixed” it. But the container is a bit large.

**Comment by w796933** [comment]
container is a bit large.  No problem

**Comment by mrenker** [comment]
Sorry to revive this, but how do I get it to update acme? I ran the update.sh and manually updated the acme folder but the error still occurs...

`acme-mailcow_1       | acme-client: transfer buffer: [{ "type": "urn:acme:error:malformed", "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]", "status": 400 }] (267 bytes)`

**Comment by stevesbrain** [comment]
@smillingDeath So your acme version is 1.24 in `docker images`? Because that looks to be the build which includes https://github.com/mailcow/mailcow-dockerized/blob/e4b91e06a393fa796f8875822398a3b258d2fe70/data/Dockerfiles/acme/Dockerfile#L24

**Comment by mrenker** [comment]
@stevesbrain apparently I´m using Version 1.17, but I just ran the update.sh and rebuild the image...
`mailcow/acme        1.17                0161d9b6fba7        34 seconds ago      49.6MB`
And ofc I still get the same error

**Comment by stevesbrain** [comment]
@smillingDeath Any errors in the update script? Are you running the latest version of update.sh? Normally this is auto updated, but if you're on an old version, it may not. Run a `git pull` in your repo directory to confirm you're at the latest revision for it (check the hash with `git rev-parse HEAD` to make sure it matchces master), and run `update.sh` again to check. If you're still on the old acme version, manually pull a newer one.

**Comment by mrenker** [comment]
@stevesbrain thanks for your help, git never pulled updates, because I had a change in the sogo.conf

**Comment by stevesbrain** [comment]
@smillingDeath Glad it's sorted :)
